name: kattrick
description: "Kattrick - רשת חברתית לכדורגל שכונתי בישראל. מצא שחקנים, Hubs ומגרשים, ארגן משחקים, וצור קהילה פעילה סביב הכדורגל!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.9.0
  flutter_rating_bar: ^4.0.0
  fl_chart: ^0.68.0
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.0.0
  firebase_crashlytics: ^4.0.0
  firebase_analytics: ^11.0.0
  firebase_remote_config: ^5.0.0
  cloud_functions: ^5.1.2
  firebase_app_check: ^0.3.2+10
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4
  # Localization & Intl
  intl: ^0.20.2
  # Sharing & URL Launcher
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  # Image Picker
  image_picker: ^1.1.2
  # Image Caching
  cached_network_image: ^3.3.1
  # SVG Support
  flutter_svg: ^2.0.10+1
  # Connectivity
  connectivity_plus: ^6.0.0
  # Shimmer effect for skeleton loaders
  shimmer: ^3.0.0
  # Permissions
  permission_handler: ^11.3.1
  # Contacts
  flutter_contacts: ^1.1.9
  # Location & Maps
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  # google_maps_flutter version set below with cluster_manager
  # HTTP requests
  http: ^1.2.0
  # Image processing (compression/resizing)
  image: ^4.2.0
  # Freezed + JSON Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  # Routing
  go_router: ^14.2.7
  flutter_dotenv: ^6.0.0
  flutter_speed_dial: ^7.0.0
  uuid: ^4.4.2
  sliver_tools: ^0.2.12
  # Reactive Programming
  rxdart: ^0.28.0
  google_maps_flutter: ^2.5.0
  # google_maps_cluster_manager: disabled due to name conflicts with google_maps_flutter_platform_interface
  # TODO: Re-enable when fixed - see https://github.com/google/flutter-google-maps-clustering/issues

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Testing
  mocktail: ^1.0.0
  # Build tools
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - .env
    - assets/logo/
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#0B0C10"
  image: assets/logo/KattruckLOGOFULL.png
  android_12:
    color: "#0B0C10"
    image: assets/logo/KattruckLOGOFULL.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo/KattruckLOGOFULL.png

# Remove overrides - let version resolution work naturally
